---
booktitle: Proceedings of the Fourth International Workshop on Feature Selection in
  Data Mining
shortname: FSDM
month: 0
publisher: PMLR
volume: 10
year: '2010'
start: 2010-06-21
end: 2010-06-21
published: 2010-05-26
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: LiuFeature2010
cycles: false
editor:
- given: Huan
  family: Liu
- given: Hiroshi
  family: Motoda
- given: Rudy
  family: Setiono
- given: Zheng
  family: Zhao
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Fourth International Workshop on Feature Selection in Data Mining
    Held in Hyderabad, India on 21 June 2010

  Published as Volume 10 by the Proceedings of Machine Learning Research on 26 May 2010.

  Volume Edited by:
    Huan Liu
    Hiroshi Motoda
    Rudy Setiono
    Zheng Zhao

  Series Editors:
    Neil D. Lawrence
date_str: 21 Jun
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v10"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v10
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Feature Selection in Data Mining
  url: 
  location: Hyderabad, India
  dates:
  - 2010-06-21
  number: 4
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
